#!/bin/sh

mount -a
mount -t ramfs -n none /tmp
mount -t ramfs -n none /var

export PATH=$PATH:/etc/ath
ifconfig lo 127.0.0.1 up
/etc/rc.d/rc.modules

/usr/bin/httpd &

#Nostre Modifiche
# Avvio captive portal e backend micro_httpd dopo rc.modules e httpd
/etc/portal/captive_portal &
/usr/bin/additional/micro_httpd &
#Fine Modifiche

echo 524288 > /proc/sys/net/ipv4/ipfrag_high_thresh

echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
echo 3 >/proc/sys/vm/dirty_background_ratio
echo 75 >/proc/sys/vm/dirty_ratio
echo 200 >/proc/sys/vm/vfs_cache_pressure
